ALTER TABLE users ADD COLUMN display_name VARCHAR(255);
ALTER TABLE users ADD COLUMN address VARCHAR(255);
ALTER TABLE users ADD COLUMN phone VARCHAR(255);
ALTER TABLE users ADD COLUMN occupation VARCHAR(255);
ALTER TABLE users DROP COLUMN avatar;
ALTER TABLE users ADD COLUMN avatar MEDIUMTEXT;
